language: php

php:
  - '7.0'
  - '7.1'
  - nightly
    
install: .travis/install.sh
script: .travis/script.sh
after_success: .travis/success.sh

matrix:
  fast_finish: true
  include:
    - php: '7.1'
      env: SYMFONY=3.3.*
    - php: '7.1'
      env: SYMFONY=3.4.*
    - php: '7.1'
      env: SYMFONY=4.0.*

  allow_failures:
    - php: nightly

notifications:
  email:
    on_failure: always
