language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly
    
install: .travis/install.sh
script: .travis/script.sh

matrix:
  fast_finish: true
  include:
    - php: '7.1'
      env: SYMFONY=2.8.*
    - php: '7.1'
      env: SYMFONY=3.1.*
    - php: '7.1'
      env: SYMFONY=3.2.*
    - php: '7.1'
      env: SYMFONY=3.3.*

  allow_failures:
    - php: nightly

notifications:
  email:
    on_failure: always
